apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: hello-world
images:
  - name: apps/demo
    newName: localhost:5000/apps/spring-petclinic
resources:
- deployment.yaml
