apiVersion: builtin
kind: PatchTransformer
metadata:
  name: set-volumes
target:
  group: apps
  version: v1
  kind: Deployment
  name: app
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: app
  spec:
    template:
      spec:
        containers:
        - name: app
          volumeMounts:
          - name: mysql
            mountPath: /config/bindings/mysql/meta
        volumes:
        - name: mysql
          configMap:
            name: mysql-config
