apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: petclinic
spec:
  # direct Secret reference is used for compatibility, but not recommended for dynamically provisioned services
  service:
    apiVersion: v1
    kind: Secret
    name: mysql-config
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic