apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: SERVICE_BINDING_ROOT
          value: /config/bindings
        - name: DATABASE
          value: mysql
        - name: MYSQL_HOST
          value: $(MYSQL_HOST)
        volumeMounts:
        - name: mysql
          mountPath: /config/bindings/mysql
      volumes:
      - name: mysql
        secret:
          secretName: mysql-config