apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: apps/demo
        name: app
        envFrom:
        - configMapRef:
            name: env-config
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dspring.devtools.restart.enabled=true
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 4000m
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
