apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: apps/demo
    newName: localhost:5000/apps/spring-petclinic
resources:
- deployment.yaml
- mysql.yaml
- pvc.yaml
- config.yaml
secretGenerator:
  - name: mysql-config
    behavior: merge
    envs:
      - application.env
vars:
  - name: MYSQL_HOST
    objref:
      apiVersion: v1
      kind: Service
      name: mysql
configurations:
  - varreference.yaml