apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: apps/demo
    newName: localhost:5000/apps/spring-petclinic
resources:
- deployment.yaml
- mysql.yaml
- pvc.yaml
- config.yaml
configMapGenerator:
  - name: env-config
    behavior: merge
    literals:
      - SPRING_CONFIG_LOCATION=classpath:/,file:///config/bindings/mysql/meta/
      - DATABASE=mysql
  - name: mysql-config
    behavior: merge
    files:
      - application.properties
  - name: mysql-env
    behavior: merge
    literals:
      - MYSQL_HOST=$(MYSQL_HOST)
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
vars:
  - name: MYSQL_HOST
    objref:
      apiVersion: v1
      kind: Service
      name: mysql
configurations:
  - varreference.yaml