apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql.yaml
- pvc.yaml
- config.yaml
secretGenerator:
  - name: mysql-config
    behavior: merge
    envs:
      - application.env