apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - image: springcloud/configserver
          name: configserver
---

apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8888
  selector:
    app: configserver
